修改密码时，引用secret传入初始化密码，重新整理了脚本缩进，规范了部分写法
Signed-off-by: 张田 <zhang_tian@inspur.com>

diff --git a/helm-charts/charts/kube-starrocks/templates/init-pwd/configmap.yaml b/helm-charts/charts/kube-starrocks/templates/init-pwd/configmap.yaml
--- a/helm-charts/charts/kube-starrocks/templates/init-pwd/configmap.yaml
+++ b/helm-charts/charts/kube-starrocks/templates/init-pwd/configmap.yaml
@@ -8,6 +8,7 @@ data:
     #!/bin/bash
 
 <<<<<<< HEAD
+<<<<<<< HEAD
     # ensure `mysql` command can be ended with 30 seconds
     # Change the root password during initial installation
     success=`mysql --connect-timeout 30 -h $1 -P $2 -u root --skip-column-names --batch -e "$3" 2>&1`
@@ -33,24 +34,34 @@ data:
     exit 0
 =======
     # ensure `mysql` command can be ended with 15 seconds
+=======
+    # ensure `mysql` command can be ended with 30 seconds
+>>>>>>> 38a7399... 修改密码时，引用secret传入初始化密码，重新整理了脚本缩进，规范了部分写法
     # Change the root password during initial installation
     success=`mysql --connect-timeout 30 -h $1 -P $2 -u root --skip-column-names --batch -e "$3" 2>&1`
+  
+    if [ $? -ne 0 ] ; then
+      echo $success
+      errcode=`echo $success | awk -F " " '{print $2}'`
+      echo "error code: $errcode"
 
-    if [ $? != 0 ] ; then
-    echo $success
-    errcode=`echo $success | awk -F " " '{print $2}'`
-    echo $errcode
+      # Password error, believed to have been changed, exiting normally
+      if [[ $errcode = '1045' || $errcode = '1064' ]] ; then
+        echo "Password error, believed to have been changed, exiting normally"
+        exit 0
+      fi
 
-    # Password error, believed to have been changed, exiting normally
-    if [ $errcode = '1045' ] ; then
-    exit 0
+      # Other unsuccessful errors, abnormal exit
+      echo "Other unsuccessful errors, abnormal exit"
+      exit 1
+
     fi
 
-    # connect unsuccessful, abnormal exit
-    if [ $errcode = '2003' ]  ; then
-    exit 1
-    fi
-
+<<<<<<< HEAD
     fi
 >>>>>>> 2c3afa7... 在初始化密码时，增加状态判断能力，当链接不通时才进行重试，当发现时密码错误时，认为上一次尝试修改密码已成功
+=======
+    echo "Successfully modified password"
+    exit 0
+>>>>>>> 38a7399... 修改密码时，引用secret传入初始化密码，重新整理了脚本缩进，规范了部分写法
 
